-- Nitwebs MySQL Database Schema for Hostinger & Local MySQL

CREATE TABLE IF NOT EXISTS `admin_users` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `username` VARCHAR(100) NOT NULL UNIQUE,
  `email` VARCHAR(255) NOT NULL DEFAULT 'admin@nitwebs.com',
  `password_hash` VARCHAR(255) NOT NULL,
  `otp_code` VARCHAR(10) DEFAULT NULL,
  `otp_expires_at` DATETIME DEFAULT NULL,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

-- Seed Default Admin User: admin / Admin@Nitwebs2026 / admin@nitwebs.com
INSERT INTO `admin_users` (`username`, `email`, `password_hash`)
VALUES ('admin', 'admin@nitwebs.com', '$2y$10$FCOxKDJqKitxzm2FoI/Yg.kB2yJDahcY9DAet6TT5pO1NnmnARXzW')
ON DUPLICATE KEY UPDATE `username`=`username`;

CREATE TABLE IF NOT EXISTS `site_content` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `navigation` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `footer` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `data` LONGTEXT NOT NULL,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `jobs` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `title` VARCHAR(255) NOT NULL,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `department` VARCHAR(100) DEFAULT '',
  `location` VARCHAR(100) DEFAULT 'Remote',
  `employment_type` VARCHAR(50) DEFAULT 'full-time',
  `min_experience` INT DEFAULT 0,
  `experience_level` VARCHAR(100) DEFAULT '',
  `salary_range` VARCHAR(100) DEFAULT '',
  `summary` TEXT,
  `description` LONGTEXT,
  `requirements` LONGTEXT,
  `status` VARCHAR(50) DEFAULT 'open',
  `posted_date` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `applications` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `job_id` VARCHAR(100) DEFAULT '0',
  `job_title` VARCHAR(255) DEFAULT '',
  `name` VARCHAR(255) NOT NULL,
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(100) DEFAULT '',
  `experience_years` INT DEFAULT 0,
  `resume_path` VARCHAR(500) NOT NULL,
  `cover_note` TEXT,
  `submitted_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `contacts` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `name` VARCHAR(255) NOT NULL,
  `company` VARCHAR(255) DEFAULT '',
  `email` VARCHAR(255) NOT NULL,
  `phone` VARCHAR(100) DEFAULT '',
  `project_type` VARCHAR(100) DEFAULT '',
  `subject` VARCHAR(255) DEFAULT '',
  `budget` VARCHAR(100) DEFAULT '',
  `message` TEXT,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `dynamic_pages` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `slug` VARCHAR(255) NOT NULL UNIQUE,
  `title` VARCHAR(255) NOT NULL,
  `meta_desc` TEXT,
  `meta_image` VARCHAR(500) DEFAULT '',
  `status` VARCHAR(50) DEFAULT 'draft',
  `sections` LONGTEXT,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;

CREATE TABLE IF NOT EXISTS `team_photos` (
  `id` INT AUTO_INCREMENT PRIMARY KEY,
  `url` VARCHAR(500) NOT NULL,
  `caption` VARCHAR(255) DEFAULT '',
  `category` VARCHAR(100) DEFAULT 'office',
  `order_index` INT DEFAULT 0,
  `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;